services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 1234567890
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - localhost

  frontend:
    build: 
      context: ./it-academy-hackaton-2024-front
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - backend
    networks:
      - localhost

  backend:
    build: 
      context: ./it-academy-hackaton-2024-back/InterestClubWebAPI
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - localhost

networks:
  localhost:
    driver: bridge
