---
- name: Deploy to server
  hosts: servers
  become: yes
  tasks:
    - name: Install docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes
      tags: install_docker

    - name: Clone repository
      git:
        repo: 'https://github.com/antoniocra04/it-academy-hackaton-2024-devops.git'
        dest: /root/repo
        version: 'main'
      tags: clone_repository

    - name: Run
      command: chdir=/root/repo bash run.sh
      tags: run

    - name: Stop
      command: chdir=/root/repo bash stop.sh
      tags: stop